eval.batch_size: 2
eval.cutoff_len: 8000
eval.dataset:
- weibo_covid_RAG
eval.dataset_dir: LLaMA-Factory/data
eval.max_new_tokens: 64
eval.max_samples: '100000'
eval.output_dir: eval_2025-10-18-05-34-47
eval.predict: true
eval.temperature: 0.95
eval.top_p: 0.7
top.booster: unsloth
top.checkpoint_path: []
top.finetuning_type: lora
top.model_name: DeepSeek-R1-0528-8B-Distill
top.quantization_bit: none
top.quantization_method: bnb
top.rope_scaling: none
top.template: deepseekr1
