eval.batch_size: 2
eval.cutoff_len: 8000
eval.dataset:
- weibo_covid_RAG
eval.dataset_dir: /root/LLaMA-Factory/data
eval.max_new_tokens: 512
eval.max_samples: '100000'
eval.output_dir: eval_2025-10-18-05-02-25
eval.predict: true
eval.temperature: 0.95
eval.top_p: 0.7
top.booster: unsloth
top.checkpoint_path: []
top.finetuning_type: lora
top.model_name: GLM-4-0414-9B-Chat
top.quantization_bit: '4'
top.quantization_method: bnb
top.rope_scaling: none
top.template: glm4
